name: issue-greeter
on:
  issues:
    types: [opened]
jobs:
  answer-issue:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          REPO: ${{ github.event.repository.name}}
          OWNER: ${{ github.event.repository.owner.login}}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          curl -s -X POST https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/comments \
            -d '{"body":"Hey ${{ github.event.issue.user.login }} - FUCK OFF!"}' \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
